Final_Project/MargProject/MargApp/MVC_WebInterface/Models/Personel/IndexModel.cs
namespace MVC_WebInterface.Models.Personel
{
    public class IndexModel
    {
        public List<PersonelDTO> Personels { get; set; }
    }
}

Final_Project/MargProject/MargApp/MVC_WebInterface/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Mvc;
using static MVC_WebInterface.Models.Shared.MvcInfos;

namespace MVC_WebInterface.Controllers
{
    public class PersonelController : BaseController
    {
        private readonly IMapper mapper;
        private readonly PersonelManager personelManager;

        public PersonelController(IMapper mapper, PersonelManager personelManager)
        {
            this.mapper = mapper;
            this.personelManager = personelManager;
        }

        public async Task<IActionResult> Index(string message)
        {
            var list = await personelManager.GetListAsync();
            var dtoList = mapper.Map<List<PersonelDTO>>(list);

            IndexModel model = new() { Personels = dtoList };
            ViewBag.Message = message;
            return View(model);
        }

        // GET: PersonelController/Details/5
        public async Task<IActionResult> Details(string sicilNo)
        {
            var personel = await personelManager.GetAsync(GetSessionUser().Name, sicilNo);
            var personelDto = mapper.Map<PersonelDTO>(personel);
            return View(personelDto);
        }

        // GET: PersonelController/Create
        public async Task<IActionResult> Create(string message)
        {
            ViewBag.Message = message;
            return View();
        }

        // POST: PersonelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonelDTO personelDTO)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (personelDTO.MezuniyetBilgisi.Equals(Mezuniyet.All))
                    {
                        ModelState.AddModelError("Validation", "Lütfen Geçerli Bir Mezuniyet Seçimi Yapınız");
                        return View(personelDTO);
                    }

                    var personel = mapper.Map<Personel>(personelDTO);
                    var result = await personelManager.AddAsync(GetSessionUser().SicilNo, personel);
                    if (result == null)
                    {
                        return View(nameof(Create), personelDTO);
                    }

                    return RedirectToAction(nameof(Index), new { message = personelDTO.PersonelAdSoyad + " Kaydı Başarıyla Gerçekleşti" });
                }
                return View(personelDTO);
            }
            catch
            {
                return View(personelDTO);
            }
        }

        // GET: PersonelController/Edit/5
        public async Task<IActionResult> Edit(string message, string sicilNo)
        {
            var personel = await personelManager.GetAsync(GetSessionUser().SicilNo, sicilNo);
            var personelDto = mapper.Map<PersonelDTO>(personel);
            ViewBag.Message = message;
            return View(personelDto);
        }

        // POST: PersonelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PersonelDTO personelDTO)
        {
            try
            {
                var personel = mapper.Map<Personel>(personelDTO);
                var result = await personelManager.UpdateAsync(GetSessionUser().SicilNo, personel, "");
                if (result == null)
                {
                    return PartialView(_Warning, "Güncelleme Sırasında Bir Hata Oluştu");
                }

                return RedirectToAction(nameof(Index), new { message = personelDTO.PersonelAdSoyad + " Güncellemesi Başarıyla Gerçekleşti" });
            }
            catch
            {
                return RedirectToAction(nameof(Index), new { message = personelDTO.PersonelAdSoyad + " Güncelleme İşlemi Sırasında Bir Hata Oluştu" });
            }
        }

        // GET: PersonelController/Delete/5
        public async Task<IActionResult> Delete(string sicilNo)
        {
            var personel = await personelManager.GetAsync(GetSessionUser().SicilNo, sicilNo);
            var personelDto = mapper.Map<PersonelDTO>(personel);
            return View(personelDto);
        }

        // POST: PersonelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(string sicilNo, string adSoyad)
        {
            try
            {
                var result = await personelManager.DeleteAsync(GetSessionUser().SicilNo, sicilNo);
                if (!result)
                    return RedirectToAction(nameof(Index), new { message = adSoyad + " Silme İşlemi Sırasında Bir Hata Oluştu" });

                return RedirectToAction(nameof(Index), new { message = adSoyad + " Silme İşlemi Başarıyla Gerçekleşti" });
            }
            catch
            {
                return RedirectToAction(nameof(Index), new { message = adSoyad + " Silme İşlemi Sırasında Bir Hata Oluştu" });
            }
        }
    }
}

Final_Project/MargProject/MargApp/MVC_WebInterface/Views/Personel/Create.cshtml
@model MVC_WebInterface.Models.DTO.PersonelDTO

@{
    ViewData["Title"] = "Yeni Kullanıcı";
}

<h1 class="mt-2">Yeni Kullanıcı</h1>

<hr />
@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div class="alert alert-success m-3 fs-14" style="min-width:30rem;">
        @ViewBag.Message
    </div>
}

<!-- Upload Multi User Modal -->
<div class="modal fade" id="upload-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Kaynak Dosya Yükleme</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-action="UploadExcelForUsers" asp-controller="Personel" data-ajax="true" data-ajax-method="POST" enctype="multipart/form-data"
                  data-ajax-loading="#spinner" data-ajax-update="#upload-result" data-ajax-complete="clearFileInput()">
                <div class="modal-body">
                    <div class="row">
                        <div>
                            <label class="me-3"><b>Dosyaları Seç : </b></label>
                            <input class="col-md-9 btn btn-primary" type="file" id="file" name="files" placeholder="" multiple />
                        </div>
                    </div>
                    <div class="row mt-2">
                        <span id="spinner" style="display:none;"> <img src="/img/loading.gif" class="loading-gif" /> </span>
                        <div id="upload-result" class="col-md-12 mt-1">  </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <!-- jquery ile istek gönder. Success dönünde mesaj yazdır -->
                    <a href="/User/DownloadTemplateToAddUser?fileName=LdapUserTemplate" class="btn btn-outline-primary me-auto">Şablonu İndir</a>
                    <input type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal" value="İptal" />
                    <input type="submit" class="btn btn-outline-primary" value="Karşıya Yükle" />
                </div>
            </form>
        </div>
    </div>
</div>

@*<input type="button" class="btn btn-outline-success ms-3" data-bs-toggle="modal" data-bs-target="#upload-modal" value="Excel İle Yükle" />

    <div class="m-1"> <b> Extension veya Masa Numarasını -1 Seçerek Sadece Active Directory İçin İşlem Yapılmasını Sağlayabilirsiniz </b> </div>*@

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" asp-controller="Personel" method="post" class="ms-5">
    <div class="form-group row">
        <label asp-for="Id" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="Id" class="form-control" autocomplete="nope" />
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>

        <label asp-for="PersonelAdSoyad" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="PersonelAdSoyad" class="form-control" autocomplete="nope" />
            <span asp-validation-for="PersonelAdSoyad" class="text-danger"></span>
        </div>

    </div>

    <div class="form-group row mt-3">
        <label asp-for="Tc" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="Tc" class="form-control" autocomplete="nope" />
            <span asp-validation-for="Tc" class="text-danger"></span>
        </div>

        <label asp-for="IkametAdresi" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <textarea id="text-ikamet" name="IkametAdresi" class="form-control" autocomplete="nope">

            </textarea>
            <span asp-validation-for="IkametAdresi" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mt-3">
        <label asp-for="Telefon" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="Telefon" class="form-control" autocomplete="nope" />
            <span asp-validation-for="Telefon" class="text-danger"></span>
        </div>

        <label asp-for="MezuniyetBilgisi" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <select asp-for="MezuniyetBilgisi" asp-items="Html.GetEnumSelectList<Mezuniyet>()" class="form-control">
                <option selected="selected" value="-1">Seçiniz..</option>
            </select>
            <span asp-validation-for="MezuniyetBilgisi" class="text-danger"></span>
        </div>

    </div>

    <div class="form-group row mt-3">
        <label asp-for="DogumYeri" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="DogumYeri" class="form-control" autocomplete="nope" />
            <span asp-validation-for="DogumYeri" class="text-danger"></span>
        </div>
        <label asp-for="DogumTarihi" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="DogumTarihi" class="form-control" autocomplete="nope" />
            <span asp-validation-for="DogumTarihi" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mt-3">
        <label asp-for="Password" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        @* <label asp-for="OrganizationalUnit" class="control-label col-md-2 text-right"></label>
            <div class="col-md-3">
            <select id="SelectOU"
            asp-for="OrganizationalUnit"
            class="form-control"
            asp-items="Html.GetEnumSelectList<OrganizationalUnit>()">
            <option selected>Grup Seçiniz ..</option>

            </select>
            <span asp-validation-for="OrganizationalUnit" class="text-danger"></span>
            </div>*@
    </div>

    <div class="row form-group mt-4">
        <input type="submit" value="Kaydet" class="offset-md-3 col-md-3 btn btn-outline-primary" />
    </div>
</form>


<div class="mt-3">
    @*<a asp-action="Index" class="btn btn-primary">Ana Listeye Dön</a>*@
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

<script type="text/javascript">

    $('option[value=0]').css("display", "none");

      $(document).ready(function () {
          $('#text-ikamet').text("");
      });

</script>
}

Final_Project/MargProject/MargApp/MVC_WebInterface/Views/Personel/Delete.cshtml
@model MVC_WebInterface.Models.DTO.PersonelDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Kullanıcı Silme</h1>

<h3>Belirtilen Kullanıcıyı Silmek İstediğinize Emin Misiniz</h3>
<div>
    <h4>Kullanıcı</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonelAdSoyad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DogumYeri)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DogumTarihi)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IkametAdresi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MezuniyetBilgisi)
        </dd>       
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a asp-action="Index">Ana Listeye Dön</a>
    </form>
</div>

Final_Project/MargProject/MargApp/MVC_WebInterface/Views/Personel/Details.cshtml
@model MVC_WebInterface.Models.DTO.PersonelDTO

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<h4>CompanyUserDTO</h4>
<hr />
<center>
    <table class="table table-striped font-weight-bold fs-14 bg-beige tab-table">
        <tbody>
            <tr>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.Id)</td>
                <td>@Model.Id</td>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.PersonelAdSoyad)</td>
                <td>@Model.PersonelAdSoyad</td>
            </tr>
              <tr>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.Tc)</td>
                <td>@Model.Tc</td>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.IkametAdresi)</td>
                <td>@Model.IkametAdresi</td>
            </tr>
            <tr>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.Telefon)</td>
                <td>@Model.Telefon</td>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.MezuniyetBilgisi)</td>
                <td>@Model.MezuniyetBilgisi</td>
            </tr>
            <tr>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.DogumYeri)</td>
                <td>@Model.DogumYeri</td>
                <td class="fw-bold">@Html.DisplayNameFor(model=>model.DogumTarihi)</td>
                <td>@Model.DogumTarihi</td>
            </tr>
          
        </tbody>
    </table>
</center>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Güncelle</a> |
    <a asp-action="Index">Ana Listeye Dön</a>
</div>

Final_Project/MargProject/MargApp/MVC_WebInterface/Views/Personel/Edit.cshtml
@model MVC_WebInterface.Models.DTO.PersonelDTO

@{
    ViewData["Title"] = "Kullanıcı Güncelle";
}

<h2 class="ms-2 mt-1">Kullanıcı Güncelle</h2>

<hr />

@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div class="alert alert-success m-3 fs-14" style="min-width:30rem;">
        @ViewBag.Message
    </div>
}
<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Edit" asp-controller="Personel" method="post" class="ms-5">

    <input type="hidden" name="Id" value="@Model.Id" />

    <div class="form-group row">
        <label asp-for="PersonelAdSoyad" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="PersonelAdSoyad" class="form-control" />
            <span asp-validation-for="PersonelAdSoyad" class="text-danger"></span>
        </div>

        <label asp-for="Telefon" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="Telefon" class="form-control" pattern="^\([0-9]{3}\)\s[0-9]{3}-[0-9]{4}$" />
            <span asp-validation-for="Telefon" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row mt-3">
        <label asp-for="Tc" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="Tc" class="form-control" autocomplete="nope" />
            <span asp-validation-for="Tc" class="text-danger"></span>
        </div>

        <label asp-for="IkametAdresi" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <textarea id="text-ikamet" asp-for="IkametAdresi" class="form-control" autocomplete="nope">

            </textarea>
            <span asp-validation-for="IkametAdresi" class="text-danger"></span>
        </div>

    </div>

    <div class="form-group row mt-3">
        <label asp-for="DogumTarihi" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="DogumTarihi" class="form-control" />
            <span asp-validation-for="DogumTarihi" class="text-danger"></span>
        </div>

        <label asp-for="DogumYeri" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="DogumYeri" class="form-control" />
            <span asp-validation-for="DogumYeri" class="text-danger"></span>
        </div>

    </div>

    <div class="form-group row mt-3">
        <label asp-for="IkametAdresi" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <input asp-for="IkametAdresi" class="form-control" />
            <span asp-validation-for="IkametAdresi" class="text-danger"></span>
        </div>
        <label asp-for="MezuniyetBilgisi" class="control-label col-md-2 text-right"></label>
        <div class="col-md-3">
            <select asp-for="MezuniyetBilgisi" asp-items="Html.GetEnumSelectList<Mezuniyet>()" class="form-control">
                <option selected="selected" value="-1">Seçiniz..</option>
            </select>
            <span asp-validation-for="MezuniyetBilgisi" class="text-danger"></span>
        </div>
    </div>


    <div class="form-group row mt-4">
        <input type="submit" value="Güncelle" class="btn btn-outline-primary w-25 ml-25 col-md-3 offset-md-3" />
        <a asp-action="Index" class="offset-md-2 col-md-3 btn btn-primary">Ana Listeye Dön</a>
    </div>
</form>


<div class="mt-3">
    
</div>


@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Final_Project/MargProject/MargApp/MVC_WebInterface/Views/Personel/Index.cshtml
@model MVC_WebInterface.Models.Personel.IndexModel

@{
    ViewData["Title"] = "Kullanıcılar";
}
@section FullScreen{
}

@section Styles{
<link rel="stylesheet" href="~/css/datatable_bootstrap4.css">
}

<!-- Personnel Delete Modal -->
<div class="modal fade" id="personnel-delete-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Personel Silme</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form asp-action="Delete" asp-controller="Personel" data-ajax="true" data-ajax-method="POST" data-ajax-loading="#spinner" data-ajax-update="#process-result">
                <input id="inp-personnel-id" name="sicilNo" type="hidden" value="" />
                <input id="inp-personnel-fullname" name="adSoyad" type="hidden" value="" />
                <div class="modal-body">
                    <div class="row text-center">
                        <div>
                            <label class="me-3"><b><span id="span-personnel"></span> </b> Personeli Silinecektir. Onaylıyor Musunuz ?</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal" value="İptal" />
                    <input type="submit" class="btn btn-outline-danger btn-send" value="Sil" />
                </div>
            </form>
            <div class="row">
                <span id="spinner" style="display:none;"> - Personel Siliniyor .. -</span>
                <div id="process-result" class="col-md-12 mb-2">  </div>
            </div>
        </div>
    </div>
</div>

<h1 class="ms-3 mt-2">Kullanıcı Listesi</h1>

@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div class="alert @(ViewBag.Message.Contains("Hata")?"alert-warning":"alert-success") m-3 fs-14" style="min-width:30rem;">
        @ViewBag.Message
    </div>
}

<p>
    <a asp-action="Create" class="btn btn-outline-primary mt-2 ms-3">Yeni Kayıt</a>
</p>

<div class="row">
    <div class="offset-md-1 col-md-10">


        <table class="table table-striped table-hover font-weight-bold fs-13 tab-datatable">
            <thead>
                <tr class="dropdown">
                    <td class="first"></td>
                    <td class="a1"></td>
                    <td class="b1"></td>
                    <td class="c1"></td>
                    <td class="d1"></td>
                    <td class="e1"></td>
                </tr>
                <tr>
                    <th class="first">Sicil No</th>
                    <th class="a1"> Ad Soyad </th>
                    <th class="b1">Telefon No</th>
                    <th class="c1">Doğum Tarihi</th>
                    <th class="d1">Doğum Yeri</th>
                    <th class="e1 text-center">İşlemler</th>
                </tr>
            </thead>
            <tfoot style="display:table-header-group">
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tfoot>
            <tbody>
                @foreach (var item in Model.Personels)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PersonelAdSoyad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Telefon)
                        </td>
                        <td>
                            @item.DogumTarihi.ToShortDateString()
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DogumYeri)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-sicilNo="@item.Id" class="ms-5 btn btn-outline-success" onclick="return valueControl(@item.Id)">Güncelle</a>
                            <a asp-action="Details" asp-route-sicilNo="@item.Id" class="ms-3 btn btn-outline-primary" onclick="return valueControl(@item.Id)">Detaylar</a>
                            <input type="button" class="btn-delete-personnel ms-3 btn btn-outline-danger"
                               data-id="@item.Id"
                               data-fullname="@item.PersonelAdSoyad"
                               data-val="@item.Id - @item.PersonelAdSoyad"
                               value="Sil" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

@section Scripts{

<script src="~/js/datatable_jquery.js"></script>
<script src="~/js/datatable_bootstrap4.js"></script>

<script type="text/javascript">

    $('.btn-delete-personnel').click(function(){
        var info=$(this).data('val');
        info=$.trim(info);

        if (!info) {
            alertToast("Lütfen Seçtiğiniz Sicil Numarasını Kontrol Ediniz");
            $('#personnel-delete-modal').modal('hide');
            return;
        }
        $('#inp-personnel-id').val($(this).data('id'));
        $('#inp-personnel-fullname').val($(this).data('fullname'));
        $('#span-personnel').text(info);
        $('#personnel-delete-modal').modal('show')
    });


     $('.tab-datatable').DataTable({
        "pagingType": "full_numbers",
        "responsive": true,
        "lengthChange": true,
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Hepsi"]],
        "dom": 'Blfrtip',
        "searching": true,
        "language": {
            "emptyTable": "Tabloda herhangi bir veri mevcut değil",
            "info": "_TOTAL_ kayıttan _START_ - _END_ arasındaki kayıtlar gösteriliyor",
            "infoEmpty": "Kayıt yok",
            "infoFiltered": "(_MAX_ kayıt içerisinden bulunan)",
            "infoThousands": ".",
            "lengthMenu": "Sayfada _MENU_ kayıt göster",
            "loadingRecords": "Yükleniyor...",
            "processing": "İşleniyor...",
            "search": "Ara:",
            "zeroRecords": "Eşleşen kayıt bulunamadı",
            "paginate": {
                "first": "İlk",
                "last": "Son",
                "next": "Sonraki",
                "previous": "Önceki"
            }
        },
        "order": [],

        initComplete: function () { // After DataTable initialized
            this.api().columns([0, 1, 2, 3, 4, 5, 6, 7])
                .every(function () {
                    /* use of [1,2,3] for second, third and fourth column.  Leave blank - columns() - for all.
                    Multiples? Use columns[0,1]) for first and second, e.g. */
                    var column = this;
                    var select = $('<select><option value=""/></select>')
                        .appendTo($(column.footer()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );
                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });
                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                }); // this.api function
        } //initComplete function
    }); // .DataTable function


</script>
}